#!/bin/bash

# -------------------------------------------------------------------------------
# Author: 	    Michael DeGuzis
# Git:		      https://github.com/ProfessorKaos64/SteamOS-Tools
# Scipt Name:	  build-test-chroot.sh
# Script Ver:	  0.1.3
# Description:	Builds a Debian Wheezy / SteamOS docker application container 
#               for testing purposes.
#               See: http://bit.ly/1GPw9lb (Digital Ocean Wiki)
#
# Usage:	      ./build-test-docker.sh [options] [application] 
#		            ./build-test-docker.sh --help for help
#
# Warning:	    You MUST have the Debian repos added properly for
#		            Installation of the pre-requisite packages.
#
# -------------------------------------------------------------------------------

# IN PROGRESS
# TODO: arguments specification, help file, install, removal, test options.

# Obtaining Docker
# curl -sSL https://get.docker.com/ | sed "s/|debian/|steamos|debian/g"|sh
