try{
'use strict';var l,n=this,q=function(a){a.B=function(){return a.S?a.S:a.S=new a}},aa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&
"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},t=function(a){return"array"==aa(a)},ba=function(a){var b=aa(a);return"array"==b||"object"==b&&"number"==typeof a.length},u=function(a){return"string"==typeof a},ca=function(a){return"function"==aa(a)},da=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},ga=function(a){return a[ea]||(a[ea]=++fa)},
ea="closure_uid_"+(1E9*Math.random()>>>0),fa=0,ha=function(a,b,c){return a.call.apply(a.bind,arguments)},ia=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},w=function(a,b,c){w=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ha:ia;return w.apply(null,
arguments)},ja=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}},x=Date.now||function(){return+new Date},y=function(a,b){function c(){}c.prototype=b.prototype;a.H=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.X=function(a,c,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[c].apply(a,g)}};
var z=function(){this.i=this.i;this.h=this.h};z.prototype.i=!1;z.prototype.R=function(){this.i||(this.i=!0,this.g())};var ka=function(a,b){a.i?b.call(void 0):(a.h||(a.h=[]),a.h.push(b))};z.prototype.g=function(){if(this.h)for(;this.h.length;)this.h.shift()()};var la=function(a){a&&"function"==typeof a.R&&a.R()};
var A=function(a,b){this.type=a;this.a=this.target=b;this.U=!0};A.prototype.g=function(){this.U=!1};var ma=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},ua=function(a){if(!na.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(oa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(pa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(qa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(ra,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(sa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(ta,"&#0;"));return a},oa=/&/g,pa=/</g,qa=/>/g,ra=/"/g,sa=/'/g,ta=/\x00/g,na=/[\x00&<>"']/,
wa=function(a){var b={"&amp;":"&","&lt;":"<","&gt;":">","&quot;":'"'},c;c=n.document.createElement("div");return a.replace(va,function(a,e){var f=b[a];if(f)return f;if("#"==e.charAt(0)){var g=Number("0"+e.substr(1));isNaN(g)||(f=String.fromCharCode(g))}f||(c.innerHTML=a+" ",f=c.firstChild.nodeValue.slice(0,-1));return b[a]=f})},xa=function(a){return a.replace(/&([^;]+);/g,function(a,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if("#"==c.charAt(0)){var d=
Number("0"+c.substr(1));if(!isNaN(d))return String.fromCharCode(d)}return a}})},va=/&([^;\s<&]+);?/g,B=function(a){return null==a?"":String(a)},ya=function(a,b){return a<b?-1:a>b?1:0},za=function(a){isFinite(a)&&(a=String(a));return u(a)?/^\s*-?0x/i.test(a)?parseInt(a,16):parseInt(a,10):NaN};
var Aa=function(a){A.call(this,a);this.h=0;this.c=null;this.l=this.s="";this.o=0;this.i=""};y(Aa,A);var Ba=function(a,b,c,d,e){var f=new Aa("clip_changed");f.c=a;f.h=b;f.s=c;f.l=d;e&&(f.o=e.i,f.i=e.A());return f};Aa.prototype.D=function(){return B(this.c&&this.c.A()||null)};
var C=Array.prototype,Ca=C.indexOf?function(a,b,c){return C.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(u(a))return u(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Da=C.forEach?function(a,b,c){C.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=u(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Ea=C.map?function(a,b,c){return C.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=u(a)?a.split(""):
a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e},Fa=function(a){return C.concat.apply(C,arguments)},Ga=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},Ha=function(a,b){for(var c=b||function(){return da(g)?"o"+ga(g):(typeof g).charAt(0)+g},d={},e=0,f=0;f<a.length;){var g=a[f++],h=c(g);Object.prototype.hasOwnProperty.call(d,h)||(d[h]=!0,a[e++]=g)}a.length=e},Ia=function(a,b){return a>b?1:a<b?-1:0};
var Ja=n.JSON.stringify;var Ka=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},La=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b},Ma="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),Na=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ma.length;f++)c=Ma[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}},Oa=function(a){var b=arguments.length;if(1==b&&t(arguments[0]))return Oa.apply(null, arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};
var D=function(){},E=function(a,b,c,d){a.a=null;b||(b=[]);a.l=void 0;a.i=-1;a.c=b;a:{if(a.c.length){b=a.c.length-1;var e=a.c[b];if(e&&"object"==typeof e&&!t(e)){a.h=b-a.i;a.g=e;break a}}-1<c?(a.h=c,a.g=null):a.h=Number.MAX_VALUE}if(d)for(c=0;c<d.length;c++)b=d[c],b<a.h?(b+=a.i,a.c[b]=a.c[b]||Pa):a.g[b]=a.g[b]||Pa},Pa=[],F=function(a,b){if(b<a.h){var c=b+a.i,d=a.c[c];return d===Pa?a.c[c]=[]:d}d=a.g[b];return d===Pa?a.g[b]=[]:d},G=function(a,b,c){b<a.h?a.c[b+a.i]=c:a.g[b]=c},H=function(a,b,c){a.a||
(a.a={});if(!a.a[c]){var d=F(a,c);d&&(a.a[c]=new b(d))}return a.a[c]},I=function(a,b,c){a.a||(a.a={});var d=c?c.c:c;a.a[b]=c;G(a,b,d)};D.prototype.m=function(){return n.JSON&&n.JSON.stringify?n.JSON.stringify(this.c):Ja(this.c)};D.prototype.toString=function(){return this.c.toString()};
var Ra=function(a){var b=Qa;if(a.g){a.a||(a.a={});var c=b.c;if(b.g){if(b.a)return a.a[c]||(a.a[c]=Ea(a.g[c]||[],function(a){return new b.a(a)})),a.a[c]}else if(b.a)return!a.a[c]&&a.g[c]&&(a.a[c]=new b.a(a.g[c])),a.a[c];return a.g[c]}},Sa=function(a){var b;if(t(a)){for(var c=Array(a.length),d=0;d<a.length;d++)null!=(b=a[d])&&(c[d]="object"==typeof b?Sa(b):b);return c}c={};for(d in a)null!=(b=a[d])&&(c[d]="object"==typeof b?Sa(b):b);return c};
var Ua=function(a){E(this,a,-1,Ta)};y(Ua,D);var Ta=[3];Ua.prototype.getTitle=function(){return F(this,2)};Ua.prototype.setTitle=function(a){G(this,2,a)};var Va=function(a){this.a=a||new Ua};Va.prototype.setTitle=function(a){this.a.setTitle(a)};Va.prototype.m=function(){return this.a.m()};var Wa=function(a){E(this,a,-1,null)};y(Wa,D);var K=function(a){return H(a,J,2)},J=function(a){E(this,a,-1,null)};y(J,D);var Xa=function(a){return F(a,1)};var Ya=function(a){E(this,a,-1,null)};y(Ya,D);Ya.prototype.A=function(){return F(this,1)};var Za=function(a){E(this,a,-1,null)};y(Za,D);Za.prototype.getTitle=function(){return F(this,1)};Za.prototype.setTitle=function(a){G(this,1,a)};var $a=function(a){E(this,a,-1,null)};y($a,D);var ab=function(a){E(this,a,-1,null)};y(ab,D);var cb=function(a){E(this,a,22,bb)};y(cb,D);var bb=[3];cb.prototype.D=function(){return H(this,Ya,1)};var db=function(a){E(this,a,-1,null)};y(db,D);var fb=function(a){this.a=a||new db};fb.prototype.m=function(){return this.a.m()};var gb;a:{var hb=n.navigator;if(hb){var ib=hb.userAgent;if(ib){gb=ib;break a}}gb=""}var L=function(a){return-1!=gb.indexOf(a)};var jb=function(){return L("Opera")||L("OPR")},kb=function(){return L("Edge")||L("Trident")||L("MSIE")},lb=function(){return(L("Chrome")||L("CriOS"))&&!jb()&&!kb()};var M=function(){return L("Edge")};var mb=jb(),N=kb(),nb=L("Gecko")&&!(-1!=gb.toLowerCase().indexOf("webkit")&&!M())&&!(L("Trident")||L("MSIE"))&&!M(),ob=-1!=gb.toLowerCase().indexOf("webkit")&&!M(),pb=function(){var a=gb;if(nb)return/rv\:([^\);]+)(\)|;)/.exec(a);if(N&&M())return/Edge\/([\d\.]+)/.exec(a);if(N)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(ob)return/WebKit\/(\S+)/.exec(a)},qb=function(){var a=n.document;return a?a.documentMode:void 0},rb=function(){if(mb&&n.opera){var a=n.opera.version;return ca(a)?a():a}var a=
"",b=pb();b&&(a=b?b[1]:"");return N&&!M()&&(b=qb(),b>parseFloat(a))?String(b):a}(),sb={},O=function(a){var b;if(!(b=sb[a])){b=0;for(var c=ma(String(rb)).split("."),d=ma(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"",k=/(\d*)(\D*)/g,p=/(\d*)(\D*)/g;do{var m=k.exec(g)||["","",""],r=p.exec(h)||["","",""];if(0==m[0].length&&0==r[0].length)break;b=ya(0==m[1].length?0:parseInt(m[1],10),0==r[1].length?0:parseInt(r[1],10))||ya(0==m[2].length,0==r[2].length)|| ya(m[2],r[2])}while(0==b)}b=sb[a]=0<=b}return b},tb=n.document,ub=qb(),vb=!tb||!N||!ub&&M()?void 0:ub||("CSS1Compat"==tb.compatMode?parseInt(rb,10):5);
var wb=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,zb=function(a){if(xb){xb=!1;var b=n.location;if(b){var c=b.href;if(c&&(c=yb(zb(c)[3]||null))&&c!=b.hostname)throw xb=!0,Error();}}return a.match(wb)},xb=ob,yb=function(a){return a?decodeURI(a):a},Ab=function(a,b){for(var c=a.split("&"),d=0;d<c.length;d++){var e=c[d].indexOf("="),f=null,g=null;0<=e?(f=c[d].substring(0,e),g=c[d].substring(e+1)):f=c[d];b(f,g?decodeURIComponent(g.replace(/\+/g, " ")):"")}};
var Bb="StopIteration"in n?n.StopIteration:{message:"StopIteration",stack:""},Cb=function(){};Cb.prototype.next=function(){throw Bb;};Cb.prototype.N=function(){return this};var P=function(a,b){this.c={};this.a=[];this.h=this.g=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){if(a instanceof P)d=a.F(),c=a.v();else{var c=[],e=0;for(d in a)c[e++]=d;d=c;c=La(a)}for(e=0;e<d.length;e++)this.set(d[e],c[e])}};P.prototype.v=function(){Db(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.c[this.a[b]]);return a};P.prototype.F=function(){Db(this);return this.a.concat()};
P.prototype.G=function(){return 0==this.g};P.prototype.remove=function(a){return Q(this.c,a)?(delete this.c[a],this.g--,this.h++,this.a.length>2*this.g&&Db(this),!0):!1};var Db=function(a){if(a.g!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];Q(a.c,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.g!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],Q(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};l=P.prototype;l.get=function(a,b){return Q(this.c,a)?this.c[a]:b};
l.set=function(a,b){Q(this.c,a)||(this.g++,this.a.push(a),this.h++);this.c[a]=b};l.forEach=function(a,b){for(var c=this.F(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};l.clone=function(){return new P(this)};l.N=function(a){Db(this);var b=0,c=this.h,d=this,e=new Cb;e.next=function(){if(c!=d.h)throw Error("The map has changed since the iterator was created");if(b>=d.a.length)throw Bb;var e=d.a[b++];return a?e:d.c[e]};return e}; var Q=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
var Eb=function(a){if("function"==typeof a.v)return a.v();if(u(a))return a.split("");if(ba(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return La(a)};var R=function(a,b){this.c=this.s=this.g="";this.o=null;this.h=this.a="";this.i=!1;var c;a instanceof R?(this.i=void 0!==b?b:a.i,Fb(this,a.g),this.s=a.s,this.c=a.c,Gb(this,a.o),this.a=a.a,Hb(this,a.l.clone()),this.h=a.h):a&&(c=zb(String(a)))?(this.i=!!b,Fb(this,c[1]||"",!0),this.s=Ib(c[2]||""),this.c=Ib(c[3]||"",!0),Gb(this,c[4]),this.a=Ib(c[5]||"",!0),Hb(this,c[6]||"",!0),this.h=Ib(c[7]||"")):(this.i=!!b,this.l=new Jb(null,0,this.i))};
R.prototype.toString=function(){var a=[],b=this.g;b&&a.push(Kb(b,Lb,!0),":");if(b=this.c){a.push("//");var c=this.s;c&&a.push(Kb(c,Lb,!0),"@");a.push(encodeURIComponent(String(b)).replace(/%25([0-9a-fA-F]{2})/g,"%$1"));b=this.o;null!=b&&a.push(":",String(b))}if(b=this.a)this.c&&"/"!=b.charAt(0)&&a.push("/"),a.push(Kb(b,"/"==b.charAt(0)?Mb:Nb,!0));(b=this.l.toString())&&a.push("?",b);(b=this.h)&&a.push("#",Kb(b,Ob));return a.join("")};R.prototype.clone=function(){return new R(this)};
var Fb=function(a,b,c){a.g=c?Ib(b,!0):b;a.g&&(a.g=a.g.replace(/:$/,""))},Gb=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.o=b}else a.o=null},Hb=function(a,b,c){b instanceof Jb?(a.l=b,Pb(a.l,a.i)):(c||(b=Kb(b,Qb)),a.l=new Jb(b,0,a.i))},Rb=function(a){return a instanceof R?a.clone():new R(a,void 0)},Ib=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},Kb=function(a,b,c){return u(a)?(a=encodeURI(a).replace(b,Sb),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,
"%$1")),a):null},Sb=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Lb=/[#\/\?@]/g,Nb=/[\#\?:]/g,Mb=/[\#\?]/g,Qb=/[\#\?@]/g,Ob=/#/g,Jb=function(a,b,c){this.g=this.a=null;this.c=a||null;this.h=!!c},S=function(a){a.a||(a.a=new P,a.g=0,a.c&&Ab(a.c,function(b,c){var d=decodeURIComponent(b.replace(/\+/g," "));S(a);a.c=null;var d=Tb(a,d),e=a.a.get(d);e||a.a.set(d,e=[]);e.push(c);a.g++}))};
Jb.prototype.remove=function(a){S(this);a=Tb(this,a);return Q(this.a.c,a)?(this.c=null,this.g-=this.a.get(a).length,this.a.remove(a)):!1};Jb.prototype.G=function(){S(this);return 0==this.g};var Ub=function(a,b){S(a);b=Tb(a,b);return Q(a.a.c,b)};l=Jb.prototype;l.F=function(){S(this);for(var a=this.a.v(),b=this.a.F(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};
l.v=function(a){S(this);var b=[];if(u(a))Ub(this,a)&&(b=Fa(b,this.a.get(Tb(this,a))));else{a=this.a.v();for(var c=0;c<a.length;c++)b=Fa(b,a[c])}return b};l.set=function(a,b){S(this);this.c=null;a=Tb(this,a);Ub(this,a)&&(this.g-=this.a.get(a).length);this.a.set(a,[b]);this.g++;return this};l.get=function(a,b){var c=a?this.v(a):[];return 0<c.length?String(c[0]):b};
l.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.F(),c=0;c<b.length;c++)for(var d=b[c],e=encodeURIComponent(String(d)),d=this.v(d),f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}return this.c=a.join("&")};l.clone=function(){var a=new Jb;a.c=this.c;this.a&&(a.a=this.a.clone(),a.g=this.g);return a};
var Tb=function(a,b){var c=String(b);a.h&&(c=c.toLowerCase());return c},Pb=function(a,b){b&&!a.h&&(S(a),a.c=null,a.a.forEach(function(a,b){var e=b.toLowerCase();b!=e&&(this.remove(b),this.remove(e),0<a.length&&(this.c=null,this.a.set(Tb(this,e),Ga(a)),this.g+=a.length))},a));a.h=b};
var Vb=function(a){this.a=a||new Za;a=F(this.a,3);G(this.a,3,a)};Vb.prototype.getTitle=function(){return B(this.a.getTitle())};Vb.prototype.setTitle=function(a){this.a.setTitle(a)};Vb.prototype.m=function(){return this.a.m()};Oa("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));var Wb=function(){this.c="";this.a=null},Xb=function(a){var b=new Wb;b.c=a;b.a=0};Xb("<!DOCTYPE html>");Xb("");var Zb=function(a){this.a=new P;if(a){a=Eb(a);for(var b=a.length,c=0;c<b;c++){var d=a[c];this.a.set(Yb(d),d)}}},Yb=function(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+ga(a):b.substr(0,1)+a};l=Zb.prototype;l.removeAll=function(a){a=Eb(a);for(var b=a.length,c=0;c<b;c++)this.remove(a[c])};l.remove=function(a){return this.a.remove(Yb(a))};l.G=function(){return this.a.G()};l.v=function(){return this.a.v()};l.clone=function(){return new Zb(this)};l.N=function(){return this.a.N(!1)};
var $b=function(a,b,c,d,e){this.reset(a,b,c,d,e)};$b.prototype.a=null;var ac=0;$b.prototype.reset=function(a,b,c,d,e){"number"==typeof e||ac++;this.g=d||x();this.h=a;this.i=b;this.c=c;delete this.a};$b.prototype.getMessage=function(){return this.i};var bc=function(a){this.h=a;this.c=this.g=this.a=null},cc=function(a,b){this.name=a;this.value=b};cc.prototype.toString=function(){return this.name};var dc=new cc("SHOUT",1200),gc=new cc("SEVERE",1E3),hc=new cc("WARNING",900),ic=new cc("INFO",800),jc=new cc("CONFIG",700);bc.prototype.getChildren=function(){this.c||(this.c={});return this.c};var kc=function(a){return a.g?a.g:a.a?kc(a.a):null};
bc.prototype.log=function(a,b,c){if(a.value>=kc(this).value)for(ca(b)&&(b=b()),a=new $b(a,String(b),this.h),c&&(a.a=c),c="log:"+a.getMessage(),n.console&&(n.console.timeStamp?n.console.timeStamp(c):n.console.markTimeline&&n.console.markTimeline(c)),n.msWriteProfilerMark&&n.msWriteProfilerMark(c),c=this;c;)c=c.a}; var lc={},mc=null,nc=function(){mc||(mc=new bc(""),lc[""]=mc,mc.g=jc)},T=function(a){nc();var b;if(!(b=lc[a])){b=new bc(a);var c=a.lastIndexOf("."),d=a.substr(c+1),c=T(a.substr(0,c));c.getChildren()[d]=b;b.a=c;lc[a]=b}return b};
!L("Android")||lb()||L("Firefox")||jb();lb();T("gws.collections.models.IndexedClips");T("gws.collections.models.IndexedFolios");var oc=function(){};q(oc);var pc={0:"c_",1:"f_",2:"d_",3:"g_",4:"lc_",5:"lf_"},qc=function(a){return pc[a]+(839808*a+Math.floor(839808*Math.random())).toString(36)+x().toString(36)};var rc=function(a,b,c){A.call(this,c||"TRANSACTION_COMMIT");this.i=a||0;(a=b)||(oc.B(),a=qc(2));this.h=a;this.c=[];this.l=[]};y(rc,A);var tc=function(a,b,c){a.c.push(b);a.l.push(c);sc(c,b)};rc.prototype.A=function(){return this.h};var uc=!N||N&&(M()||9<=vb),vc=N&&!O("9");!ob||O("528");nb&&O("1.9b")||N&&O("8")||mb&&O("9.5")||ob&&O("528");nb&&!O("8")||N&&O("9");var wc=function(a){wc[" "](a);return a};wc[" "]=function(){};var xc=function(a,b){A.call(this,a?a.type:"");this.c=this.state=this.a=this.target=null;if(a){this.type=a.type;this.target=a.target||a.srcElement;this.a=b;var c=a.relatedTarget;if(c&&nb)try{wc(c.nodeName)}catch(d){}this.state=a.state;this.c=a;a.defaultPrevented&&this.g()}};y(xc,A);xc.prototype.g=function(){xc.H.g.call(this);var a=this.c;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,vc)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var yc="closure_listenable_"+(1E6*Math.random()|0),zc=function(a){return!(!a||!a[yc])},Ac=0;var Bc=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.K=!!d;this.L=e;this.O=++Ac;this.removed=this.J=!1},Cc=function(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.L=null};var Dc=function(a){this.src=a;this.a={};this.c=0},Fc=function(a,b,c,d,e,f){var g=b.toString();b=a.a[g];b||(b=a.a[g]=[],a.c++);var h=Ec(b,c,e,f);-1<h?(a=b[h],d||(a.J=!1)):(a=new Bc(c,a.src,g,!!e,f),a.J=d,b.push(a));return a};Dc.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Ec(e,b,c,d);return-1<b?(Cc(e[b]),C.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.c--),!0):!1};
var Gc=function(a,b){var c=b.type;if(!(c in a.a))return!1;var d=a.a[c],e=Ca(d,b),f;(f=0<=e)&&C.splice.call(d,e,1);f&&(Cc(b),0==a.a[c].length&&(delete a.a[c],a.c--));return f};Dc.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,Cc(d[e]);delete this.a[c];this.c--}return b}; var Hc=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=Ec(a,c,d,e));return-1<b?a[b]:null},Ec=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.K==!!c&&f.L==d)return e}return-1};
var Ic="closure_lm_"+(1E6*Math.random()|0),Jc={},Kc=0,Lc=function(a,b,c,d,e){if(t(b)){for(var f=0;f<b.length;f++)Lc(a,b[f],c,d,e);return null}c=Mc(c);return zc(a)?a.listen(b,c,d,e):Nc(a,b,c,!1,d,e)},Nc=function(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var g=!!e,h=Oc(a);h||(a[Ic]=h=new Dc(a));c=Fc(h,b,c,d,e,f);if(c.proxy)return c;d=Pc();c.proxy=d;d.src=a;d.listener=c;a.addEventListener?a.addEventListener(b.toString(),d,g):a.attachEvent(Qc(b.toString()),d);Kc++;return c},Pc=function(){var a=
Rc,b=uc?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b},Sc=function(a,b,c,d,e){if(t(b)){for(var f=0;f<b.length;f++)Sc(a,b[f],c,d,e);return null}c=Mc(c);return zc(a)?Fc(a.w,String(b),c,!0,d,e):Nc(a,b,c,!0,d,e)},Tc=function(a,b,c,d,e){if(t(b))for(var f=0;f<b.length;f++)Tc(a,b[f],c,d,e);else c=Mc(c),zc(a)?a.unlisten(b,c,d,e):a&&(a=Oc(a))&&(b=Hc(a,b,c,!!d,e))&&Uc(b)},Uc=function(a){if("number"==typeof a||!a||a.removed)return!1;var b=a.src;
if(zc(b))return Gc(b.w,a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.K):b.detachEvent&&b.detachEvent(Qc(c),d);Kc--;(c=Oc(b))?(Gc(c,a),0==c.c&&(c.src=null,b[Ic]=null)):Cc(a);return!0},Qc=function(a){return a in Jc?Jc[a]:Jc[a]="on"+a},Wc=function(a,b,c,d){var e=!0;if(a=Oc(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.K==c&&!f.removed&&(f=Vc(f,d),e=e&&!1!==f)}return e},Vc=function(a,b){var c=a.listener,d=a.L||a.src;a.J&&Uc(a);return c.call(d,
b)},Rc=function(a,b){if(a.removed)return!0;if(!uc){var c;if(!(c=b))a:{c=["window","event"];for(var d=n,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break a}c=d}e=c;c=new xc(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){a:{var f=!1;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(g){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.a;f;f=f.parentNode)e.push(f);for(var f=a.type,h=e.length-1;0<=h;h--){c.a=e[h];var k=Wc(e[h],f,!0,c),d=d&&k}for(h=0;h<e.length;h++)c.a=e[h],k=Wc(e[h],
f,!1,c),d=d&&k}return d}return Vc(a,new xc(b,this))},Oc=function(a){a=a[Ic];return a instanceof Dc?a:null},Xc="__closure_events_fn_"+(1E9*Math.random()>>>0),Mc=function(a){if(ca(a))return a;a[Xc]||(a[Xc]=function(b){return a.handleEvent(b)});return a[Xc]};
var U=function(){z.call(this);this.w=new Dc(this);this.W=this;this.s=null};y(U,z);U.prototype[yc]=!0;U.prototype.addEventListener=function(a,b,c,d){Lc(this,a,b,c,d)};U.prototype.removeEventListener=function(a,b,c,d){Tc(this,a,b,c,d)};
var sc=function(a,b){var c,d=a.s;if(d)for(c=[];d;d=d.s)c.push(d);var d=a.W,e=b,f=e.type||e;if(u(e))e=new A(e,d);else if(e instanceof A)e.target=e.target||d;else{var g=e,e=new A(f,d);Na(e,g)}var g=!0,h;if(c)for(var k=c.length-1;0<=k;k--)h=e.a=c[k],g=Yc(h,f,!0,e)&&g;h=e.a=d;g=Yc(h,f,!0,e)&&g;g=Yc(h,f,!1,e)&&g;if(c)for(k=0;k<c.length;k++)h=e.a=c[k],g=Yc(h,f,!1,e)&&g};U.prototype.g=function(){U.H.g.call(this);this.w&&this.w.removeAll(void 0);this.s=null};
U.prototype.listen=function(a,b,c,d){return Fc(this.w,String(a),b,!1,c,d)};U.prototype.unlisten=function(a,b,c,d){return this.w.remove(String(a),b,c,d)};var Yc=function(a,b,c,d){b=a.w.a[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.removed&&g.K==c){var h=g.listener,k=g.L||g.src;g.J&&Gc(a.w,g);e=!1!==h.call(k,d)&&e}}return e&&0!=d.U};
var Zc=function(){U.call(this)};y(Zc,U);var $c=function(a){U.call(this);this.a=a};y($c,Zc);$c.prototype.A=function(){return this.a.D()?B(this.a.D().A()):""};$c.prototype.m=function(){return this.a.m()};var ad=".0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz".split(""),bd={},cd;for(cd in ad)bd[ad[cd]]=cd;for(var dd in bd);var V=function(a){z.call(this);this.c=a;this.a={}};y(V,z);var ed=[];V.prototype.listen=function(a,b,c,d){t(b)||(b&&(ed[0]=b.toString()),b=ed);for(var e=0;e<b.length;e++){var f=Lc(a,b[e],c||this.handleEvent,d||!1,this.c||this);if(!f)break;this.a[f.O]=f}return this};var fd=function(a,b,c,d,e,f){if(t(c))for(var g=0;g<c.length;g++)fd(a,b,c[g],d,e,f);else(b=Sc(b,c,d||a.handleEvent,e,f||a.c||a))&&(a.a[b.O]=b)};
V.prototype.unlisten=function(a,b,c,d,e){if(t(b))for(var f=0;f<b.length;f++)this.unlisten(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.c||this,c=Mc(c),d=!!d,b=zc(a)?Hc(a.w,String(b),c,d,e):a?(a=Oc(a))?Hc(a,b,c,d,e):null:null,b&&(Uc(b),delete this.a[b.O]);return this};V.prototype.removeAll=function(){Ka(this.a,Uc);this.a={}};V.prototype.g=function(){V.H.g.call(this);this.removeAll()};V.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};
var W=function(a,b){this.width=a;this.height=b};W.prototype.clone=function(){return new W(this.width,this.height)};var gd=function(a){return a.width*a.height};W.prototype.G=function(){return!gd(this)};W.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
var id=function(a){this.a=a||new Wa;if(!K(this.a)){a=this.a;var b=new J;I(a,2,b)}H(this.a,J,3)||(a=this.a,b=new J,I(a,3,b));this.c=new R(B(Xa(K(this.a))));new R(hd(this))},hd=function(a){return B(Xa(H(a.a,J,3))).replace(/^\/\//,"https://")};id.prototype.m=function(){return this.a.m()};
var jd=function(a){this.a=a||new $a};jd.prototype.m=function(){return this.a.m()};var kd=function(a){this.a=a||new ab};kd.prototype.m=function(){return this.a.m()};var ld=function(a){E(this,a,-1,null)};y(ld,D);var Qa=new function(){this.c=71309500;this.a=ld;this.g=0}(function(a,b){var c,d=F(b,1),e=F(b,2),f;if(f=c=b.getLocation())f={latitude:F(c,1),longitude:F(c,2)},a&&(f.V=c);c={Y:d,Z:e,location:f};a&&(c.V=b);return c});ld.prototype.getLocation=function(){return H(this,md,3)};var md=function(a){E(this,a,-1,null)};y(md,D);
var nd=!N||N&&(M()||9<=vb);!nb&&!N||N&&N&&(M()||9<=vb)||nb&&O("1.9.1");N&&O("9");var pd=function(a,b){Ka(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in od?a.setAttribute(od[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})},od={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"},rd=function(a,b,c){var d=arguments,e=document,
f=d[0],g=d[1];if(!nd&&g&&(g.name||g.type)){f=["<",f];g.name&&f.push(' name="',ua(g.name),'"');if(g.type){f.push(' type="',ua(g.type),'"');var h={};Na(h,g);delete h.type;g=h}f.push(">");f=f.join("")}f=e.createElement(f);g&&(u(g)?f.className=g:t(g)?f.className=g.join(" "):pd(f,g));2<d.length&&qd(e,f,d);return f},qd=function(a,b,c){function d(c){c&&b.appendChild(u(c)?a.createTextNode(c):c)}for(var e=2;e<c.length;e++){var f=c[e];!ba(f)||da(f)&&0<f.nodeType?d(f):Da(sd(f)?Ga(f):f,d)}},sd=function(a){if(a&& "number"==typeof a.length){if(da(a))return"function"==typeof a.item||"string"==typeof a.item;if(ca(a))return"function"==typeof a.item}return!1};
var X=function(a){$c.call(this,a||new cb);this.c=td(this);this.l=ud(this);this.C=vd(this);a=this.a;a.a||(a.a={});if(!a.a[3]){for(var b=F(a,3),c=[],d=0;d<b.length;d++)c[d]=new db(b[d]);a.a[3]=c}b=a.a[3];b==Pa&&(b=a.a[3]=[]);a=b;for(b=0;b<a.length;b++)c=new fb(a[b]),H(c.a,Ya,1).A();a=H(this.a,ab,10);!this.o&&a&&(this.o=new kd(a));this.o=this.o||null;a=H(this.a,$a,13);!this.I&&a&&(this.I=new jd(a));this.I=this.I||null;new Zb;this.A()||(oc.B(),a=qc(0),this.a.D()||(b=new Ya,I(this.a,1,b)),b=this.a.D(),
G(b,1,a))};y(X,$c);T("gws.collections.models.ClipModel");X.prototype.clone=function(){var a;a=this.a;a=new a.constructor(Sa(a.c));return new X(a)};var td=function(a){var b=H(a.a,Wa,5);!a.c&&b&&(a.c=new id(b));if(!a.c&&3==F(a.a,4)){var b=vd(a),b=B(F(b.a,1)).replace(/\//g,"-"),b="https://www.gstatic.com/vd/kp/%s/en/1/image.jpg".replace("%s",b),c=rd("img");c.src=b;c.onload=w(a.M,a,c)}return a.c||null};
X.prototype.M=function(a){var b=new id,c=a.src,d=H(b.a,J,3);G(d,1,c);new R(hd(b));c=a.naturalWidth;a=a.naturalHeight;d=H(b.a,J,3);G(d,2,c);c=H(b.a,J,3);G(c,3,a);var c=(a=new rc(3))||new rc,d=this.c&&this.c.m(),e=b.m();d!=e&&(this.c=b,I(this.a,5,b.a),b=x(),G(this.a,8,b),b=Ba(this,203,d||"",e,c),tc(c,b,this),c!=a&&0<c.c.length&&sc(this,c))};var vd=function(a){var b=H(a.a,Ua,9);!a.C&&b&&(a.C=new Va(b));return a.C||null},ud=function(a){var b=H(a.a,Za,6);!a.l&&b&&(a.l=new Vb(b));return a.l||null};
X.prototype.getTitle=function(){return ud(this)?ud(this).getTitle().toString():""};X.prototype.setTitle=function(a,b){var c=b||new rc;if(ud(this).getTitle()==a)return!1;var d=ud(this).m(),e=ud(this);e.setTitle(a);var f=x();G(this.a,8,f);d=Ba(this,204,d,e.m(),c);tc(c,d,this);c!=b&&0<c.c.length&&sc(this,c);return!0};var wd=function(a,b){var c=new rc,d=F(a.a,4);F(a.a,4)!=b&&(G(a.a,4,b),d=Ba(a,206,""+d,""+b,c),tc(c,d,a),void 0!=c&&0<c.c.length&&sc(a,c))}; X.prototype.toString=function(){return"ClipModel:"+this.A()};X.prototype.getLocation=function(){var a=Ra(this.a);return a&&(a=a.getLocation())?B(F(a,1).toFixed(4)+","+F(a,2).toFixed(4)):""};
var xd=function(a){var b;do b=a,a=-1!=a.indexOf("&")?"document"in n?wa(a):xa(a):a;while(a!=b);return a};var yd=function(a){z.call(this);this.l=a;this.a={};this.c={}};y(yd,z);yd.prototype.g=function(){this.unlisten();yd.H.g.call(this)};yd.prototype.listen=function(a,b){var c=w(b,this.l);a.addListener(c);var d=ga(a);d in this.a?this.c[d].a.set(Yb(c),c):(this.a[d]=a,this.c[d]=new Zb([c]));return this};yd.prototype.unlisten=function(a){if(a){var b=ga(a);if(b in this.a){var c=this.c[b].v();Da(c,a.removeListener,a);delete this.c[b];delete this.a[b]}}else Ka(this.a,this.unlisten,this)};
var zd=function(){U.call(this);this.I=new V(this);ka(this,ja(la,this.I))};y(zd,U);zd.prototype.c=function(a){this.s=a};var Y,Ad,Bd,Cd,Dd,Ed,Fd,Gd;
(function(){var a={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},b={IMG:" ",BR:"\n"};Y=function(a,b){var e=Cd(a);return e.defaultView&&e.defaultView.getComputedStyle&&(e=e.defaultView.getComputedStyle(a,null))?e[b]||e.getPropertyValue(b)||"":""};Ad=function(a){if("none"!=Y(a,"display"))return Bd(a);var b=a.style,e=b.display,f=b.visibility,g=b.position;b.visibility="hidden";b.position="absolute";b.display="inline";a=Bd(a);b.display=e;b.position=g;b.visibility=f;return a};Bd=function(a){var b=a.offsetWidth,
e=a.offsetHeight;return void 0===b||!b&&!e?(a=a.getBoundingClientRect(),new W(a.right-a.left,a.bottom-a.top)):new W(b,e)};Cd=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};Dd=function(a){if(a.parentElement)return a.parentElement;a=a.parentNode;return"object"==typeof a&&1==a.nodeType?a:null};Ed=function(a){var b=Cd(a);if(a==b.documentElement)return 0;var e=b.body||b.documentElement,b=b.defaultView.pageYOffset||e.scrollTop;return a.getBoundingClientRect().top+b};Gd=function(a){var b=
[];Fd(a,b);a=b.join("");a=a.replace(/ +/g," ");" "!=a&&(a=a.replace(/^\s*/,""));return a};Fd=function(c,d){if(!(c.nodeName in a))if(3==c.nodeType)d.push(String(c.nodeValue).replace(/(\r\n|\r|\n)/g,""));else if(c.nodeName in b)d.push(b[c.nodeName]);else for(var e=c.firstChild;e;)Fd(e,d),e=e.nextSibling}})();
var Hd=function(){this.a=["ad","advertisement","ads","sponsor","sponsored"]};Hd.prototype.filter=function(a){for(;a;){for(var b=a.classList,c=0;c<b.length;++c)for(var d=b[c].split(/\W+/),e=0;e<d.length;++e)if(0<=this.a.indexOf(d[e].toLowerCase()))return!1;a=Dd(a)}return!0};
var Id=function(a){this.a=a},Jd=function(a,b){return a==b?0:a.a-b.a};var Kd=function(){this.a=[]};Kd.prototype.filter=function(a){for(var b=0;b<this.a.length;++b)if(!this.a[b].filter(a))return!1;return!0};var Ld=function(a,b){var c=a.c(b);if(0==c.length)return null;for(var d=c[0],e=1;e<c.length;++e){var f=c[e];f.a>d.a&&(d=f)}return d};Kd.prototype.c=function(a){return Z(this,a.getElementsByTagName("*"))};var Z=function(a,b,c){for(var d=[],e=b.length,f=0;f<e;++f){var g=a.g(b[f],c);g&&d.push(g)}return d};Kd.prototype.g=function(){return null};
var Md=function(a,b,c,d){this.a=a;this.c=b;this.g=c;this.h=d};y(Md,Id);var Nd=function(){};Nd.prototype.filter=function(a){for(;a;){if("none"==Y(a,"display"))return!1;var b=Ad(a);if("hidden"==Y(a,"overflow")&&b.G()||"hidden"==Y(a,"visibility"))return!1;a=Dd(a)}return!0};var Od=function(){this.a=[];this.a.push(new Hd);this.a.push(new Nd)};y(Od,Kd);q(Od);var Pd=T("image.collections.extension.domextractor.DocumentImageExtractor"),Qd={".gif":.5},Rd=function(){this.T=0;this.P={}};Od.prototype.c=function(a){return Z(this,a.getElementsByTagName("*"),new Rd)};
Od.prototype.g=function(a,b){var c=null;switch(a.tagName.toLowerCase()){case "meta":c=Sd(a,1,"property","og:image","content")||Sd(a,.9,"name","msapplication-tileimage","content")||Sd(a,.8,"name","twitter:image","content")||Td(a);break;case "link":c=Sd(a,.7,"rel","apple-touch-icon","href")||Sd(a,.6,"rel","image_src","href")||Td(a);break;case "img":if(this.filter(a))a:{if((c=a.src)&&0!=c.lastIndexOf("data:",0)){var d=new W(a.naturalWidth,a.naturalHeight),e=Ad(a),f=gd(d)<gd(e)?d:e;if(f.width&&f.height){f=
Ud(a);c=new Md(f,c,d,e);break a}}c=null}break;default:if(this.filter(a)&&30>b.T){a:{c=Y(a,"background-image");d=Y(a,"background-repeat");e=Y(a,"background-size");if(d=c&&("no-repeat"==d||"cover"==e)&&0==c.lastIndexOf("url(",0))d=c.length-1,d=0<=d&&c.indexOf(")",d)==d;if(d&&(c=c.substr(4,c.length-5))&&0!=c.lastIndexOf("data:",0)&&(d=Ad(a),d.width&&d.height)){for(var e=Ud(a),f=a.children,g=0;g<f.length;++g){var h=f[g];if("none"!=Y(h,"display")&&gd(Ad(h))>.1*gd(d)){e*=.1;break}}c=new Md(e,c,void 0,d);
break a}c=null}c&&++b.T}}if(!c)return null;e=c.h||c.g;if(c.c!=document.location.href&&(100>e.width||100>e.height))return null;d=c.a;d/=1+Math.exp(-1E-5*gd(e));e=e.width/e.height;1>e&&(e=1/e);2<e&&(d*=.8);e=c.c;try{var k=Cd(a).documentURI,f=e;k instanceof R||(k=Rb(k));f instanceof R||(f=Rb(f));var g=k,k=f,p=g.clone(),m=!!k.g;m?Fb(p,k.g):m=!!k.s;m?p.s=k.s:m=!!k.c;m?p.c=k.c:m=null!=k.o;var r=k.a;if(m)Gb(p,k.o);else if(m=!!k.a){if("/"!=r.charAt(0))if(g.c&&!g.a)r="/"+r;else{var v=p.a.lastIndexOf("/");
-1!=v&&(r=p.a.substr(0,v+1)+r)}v=r;if(".."==v||"."==v)r="";else if(-1!=v.indexOf("./")||-1!=v.indexOf("/.")){for(var ec=0==v.lastIndexOf("/",0),eb=v.split("/"),v=[],f=0;f<eb.length;){var fc=eb[f++];"."==fc?ec&&f==eb.length&&v.push(""):".."==fc?((1<v.length||1==v.length&&""!=v[0])&&v.pop(),ec&&f==eb.length&&v.push("")):(v.push(fc),ec=!0)}r=v.join("/")}else r=v}m?p.a=r:m=""!==k.l.toString();m?Hb(p,Ib(k.l.toString())):m=!!k.h;m&&(p.h=k.h);e=p.toString()}catch(Be){return Pd&&Pd.log(ic,"Cannot resolve url: "+
e,void 0),null}p=B(yb(zb(e)[5]||null));m=p.lastIndexOf(".");0<m&&(p=Qd[p.slice(m)])&&(d*=p);if(e in b.P&&b.P[e]>d)return null;b.P[e]=d;return new Md(d,e,c.g,c.h)};
var Sd=function(a,b,c,d,e){if(B(a.getAttribute(c)).toLowerCase()==d.toLowerCase()){c=a.getAttribute(e);if(!c||0==c.lastIndexOf("data:",0))return null;d=za(a.getAttribute("data-google-stars-image-width"));e=za(a.getAttribute("data-google-stars-image-height"));if(d&&e)return a=Cd(a),"/"!=yb(zb(a.documentURI)[5]||null)&&-1==a.body.innerHTML.indexOf(c)&&(b*=.5),new Md(b,c,new W(d,e))}return null},Td=function(a){var b=a.getAttribute("itemprop");if(b&&"thumbnailurl"==b.toLowerCase()){b=a.getAttribute("href")||
a.getAttribute("content");if(!b||0==b.lastIndexOf("data:",0))return null;var c=za(a.getAttribute("data-google-stars-image-width"));a=za(a.getAttribute("data-google-stars-image-height"));if(c&&a)return new Md(.55,b,new W(c,a))}return null},Ud=function(a){a=Ed(a);return 2E3<a?0:1/(1+Math.exp(.001*a))};
var Vd=function(a,b){this.a=a;this.c=b};y(Vd,Id);var Wd=function(){this.a=[]};y(Wd,Kd);q(Wd);Wd.prototype.c=function(a){var b=Z(this,a.getElementsByTagName("meta"));b.push(Xd(a));if(a=a.defaultView)a=a.getSelection().toString(),0<a.length&&b.push(new Vd(1,a));return b};
Wd.prototype.g=function(a){var b=0,c="";switch(a.tagName.toLowerCase()){case "meta":var d=a.getAttribute("name"),e=a.getAttribute("property");if(e&&"og:description"==e.toLowerCase())b=.9;else if(d)switch(d.toLowerCase()){case "twitter:description":b=.8;break;case "description":b=.7;break;case "msapplication-tooltip":b=.6}0<b&&(c=a.getAttribute("content")||"")}c=xd(c);c=c.replace(/<[^<>]*?>/g,"");c=c.trim();return 5<c.length?(a=c,1024<a.length&&(a=a.substring(0,1021)+"..."),new Vd(b,a)):null};
var Xd=function(a){if(a.body){var b="",c="",d=0;a=a.body.innerText.replace(/(\r\n|\r|\n)/g,"\n");for(var e=a.split("\n"),f=0;f<e.length;++f){for(var b=e[f].replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,""),g=b.split(" "),h=g.length,k,p=k=0;p<b.length;++p)!/[^a-zA-Z]/.test(b.charAt(p))&&++k;if(p=64<=b.length&&8<=h&&k>=.4*b.length){for(var m=p=0;m<b.length;++m){var r=b.charAt(m);/[^a-zA-Z0-9]/.test(r)&&/[^\t\n\r ]/.test(r)&&++p}p=0<p}if(p&&24>=Yd(g))break;k>=.4*b.length&&h>d&&24>=Yd(g)&&(c=b,d=h); b=""}0==b.length&&20<c.length&&4<=d&&(b=c);a=a.replace(/[\t\r\n ]+/g," ").replace(/^[\t\r\n ]+|[\t\r\n ]+$/g,"");return new Vd(.1,b||a.substring(0,1024))}return null},Yd=function(a){for(var b=0,c=0;c<a.length;++c)b=Math.max(a[c].length,b);return b};
var Zd=function(a,b){this.a=a;this.c=b};y(Zd,Id);var $d=function(a){return a.c};var ae=function(a,b,c){this.a=a;this.g=b;this.c=c};y(ae,Id);var be=function(a,b,c,d){this.g=a;this.a=b;this.c=c;this.h=d};be.prototype.getTitle=function(){return this.g};var ce=function(){this.a=[]};y(ce,Kd);q(ce);ce.prototype.c=function(a){var b=Z(this,a.getElementsByTagName("meta")).concat(Z(this,a.getElementsByTagName("title"))),c=Z(this,a.getElementsByTagName("h1"));0<c.length?1==c.length&&(b=Fa(b,c)):(c=Z(this,a.getElementsByTagName("h2")),0<c.length?1==c.length&&(b=Fa(b,c)):(c=Z(this,a.getElementsByTagName("h3")),0<c.length&&1==c.length&&(b=Fa(b,c))));a.title&&b.push(new Zd(1,a.title));b.push(new Zd(.1,a.documentURI));return b};
ce.prototype.g=function(a){var b=0,c="";switch(a.tagName.toLowerCase()){case "title":b=.5;c=Gd(a);break;case "h1":b=.4;c=Gd(a);break;case "h2":b=.3;c=Gd(a);break;case "h3":b=.2;c=Gd(a);break;case "meta":var d=a.getAttribute("name"),e=a.getAttribute("property");if(e&&"og:title"==e.toLowerCase())b=.9;else if(d)switch(d.toLowerCase()){case "application-name":b=.8;break;case "twitter:title":b=.7;break;case "title":b=.6}0<b&&(c=a.getAttribute("content")||"")}c=xd(c.trim());return 1<c.length?new Zd(b,c): null};
var de=function(){this.a=[]};y(de,Kd);q(de);de.prototype.g=function(a){switch(a.tagName.toLowerCase()){case "meta":var b;a:{if("og:video"==B(a.getAttribute("property")).toLowerCase()){b=a.getAttribute("content");var c=za(a.getAttribute("data-google-stars-video-width"));a=za(a.getAttribute("data-google-stars-video-height"));if(b&&0<c&&0<a){b=new ae(1,b,new W(c,a));break a}}b=null}return b}return null};
var ee=function(a,b,c,d){this.g=a||ce.B();this.c=b||Wd.B();this.a=c||Od.B();this.h=d||de.B()};q(ee);var fe=function(){var a=ee.B(),b=document,c=Ld(a.g,b),d=Ld(a.c,b),e=a.a.c(b),a=Ld(a.h,b);Ha(e,function(a){return a.c});return new be(c,d,e,a)};var ge=function(a){if(!ca(a))if(a&&"function"==typeof a.handleEvent)a=w(a.handleEvent,a);else throw Error("Invalid listener argument");n.setTimeout(a,5E3)};var he=function(){this.a=0;this.h=new V(this);this.g=Promise.resolve();this.c=null},ie=T("image.collections.extension.DomController"),je=function(a){if(0==a.a){var b=document.getElementsByTagName("meta"),c=document.getElementsByTagName("link");a.a=b.length+c.length;0<a.a?(a.g=new Promise(w(function(a){this.c=a},a)),Da(b,a.s,a),Da(c,a.l,a),ge(a.c)):a.g=Promise.resolve()}return a.g};
he.prototype.s=function(a){var b="";if(a.hasAttribute("property"))switch(a.getAttribute("property").toLowerCase()){case "og:image":var b=a.getAttribute("content"),c=Dd(a).children,d=ke(c,"og:image:width"),c=ke(c,"og:image:height");0<d&&0<c&&(a.setAttribute("data-google-stars-image-width",d),a.setAttribute("data-google-stars-image-height",c));break;case "og:video":c=Dd(a).children,d=ke(c,"og:video:width"),c=ke(c,"og:video:height"),0<d&&0<c&&(a.setAttribute("data-google-stars-video-width",d),a.setAttribute("data-google-stars-video-height",
c))}else if(a.hasAttribute("name"))switch(a.getAttribute("name").toLowerCase()){case "msapplication-tileimage":case "twitter:image":b=a.getAttribute("content")}else if(a.hasAttribute("itemprop"))switch(a.getAttribute("itemprop").toLowerCase()){case "thumbnailurl":b=a.getAttribute("href")||a.getAttribute("content")}le(this,b,a)};
he.prototype.l=function(a){var b="";if(a.hasAttribute("rel"))switch(a.getAttribute("rel").toLowerCase()){case "apple-touch-icon-precomposed":case "apple-touch-icon":case "image_src":b=a.getAttribute("href")}else if(a.hasAttribute("itemprop"))switch(a.getAttribute("itemprop").toLowerCase()){case "thumbnailurl":b=a.getAttribute("href")||a.getAttribute("content")}le(this,b,a)};
var ke=function(a,b){for(var c=0;c<a.length;++c){var d=a[c];if(d.hasAttribute("property")&&d.getAttribute("property").toLowerCase()==b&&d.hasAttribute("content"))return d.getAttribute("content")}return""},le=function(a,b,c){if(!b||c.hasAttribute("data-google-stars-image-width")&&c.hasAttribute("data-google-stars-image-height"))0==--a.a&&a.c();else{var d=w(a.o,a,c);c=new Image;d=w(a.i,a,d);fd(a.h,c,["load","error"],d,void 0);c.src=b}};
he.prototype.i=function(a,b){var c=b.target;"load"==b.type?a(c.naturalWidth,c.naturalHeight):ie&&ie.log(hc,"Failed to load image "+c.src,void 0);0==--this.a&&this.c()};he.prototype.o=function(a,b,c){a.setAttribute("data-google-stars-image-width",b);a.setAttribute("data-google-stars-image-height",c)};
var me=function(){zd.call(this);this.a=null;this.o=new he;this.l=new yd(this);ka(this,ja(la,this.l))};y(me,zd);var ne=T("image.collections.extension.ContentController");me.prototype.c=function(a){me.H.c.call(this,a);this.l.listen(chrome.runtime.onMessage,this.M)};
me.prototype.M=function(a,b,c){c({received:"true"});switch(a.type){case "collect_page":if(null===this.a){b=a.clipId;c=a.userId;a=new Ya;G(a,1,b);G(a,2,c);b=new cb;I(b,1,a);a=x();G(b,7,a);G(b,8,a);this.a=new X(b);b=document.documentURI;/\.(jpg|jpeg|png|gif|bmp|svg|tiff)$/i.test(b)?wd(this.a,1):wd(this.a,2);a=new Vb;try{Rb(b)}catch(d){b=encodeURI(b)}try{Rb(b)}catch(e){b=""}G(a.a,3,b);b=this.a;b.l=a;I(b.a,6,a.a);je(this.o).then(w(this.C,this,!0))}else ne&&ne.log(hc,"Clip is already being created",void 0);
break;case "get_salient_images":je(this.o).then(w(this.C,this,!1));break;default:ne&&ne.log(gc,"Invalid message type: "+a.type,void 0)}};
me.prototype.C=function(a){var b=fe(),c=b.c;c.sort(Jd||Ia);for(var d=[],e=null,f=0;f<c.length;f++){var g=e=new id,h=c[f].c;g.c=null;try{var k=K(g.a);G(k,1,h);g.c=new R(B(Xa(K(g.a))))}catch(p){h=K(g.a),G(h,1,void 0),h=K(g.a),G(h,2,void 0),h=K(g.a),G(h,3,void 0)}g.c&&F(g.a,6)&&G(g.a,6,!1);var m=c[f].g;if(m){var g=e,h=m.width,m=m.height,r=K(g.a);G(r,2,h);g=K(g.a);G(g,3,m)}d.unshift(e.m())}if(a){!td(this.a)&&e&&(a=this.a,c=e,a.c=c,I(a.a,5,c.a),c=x(),G(a.a,8,c));a=ud(this.a);!a.getTitle()&&b.getTitle()&&
a.setTitle($d(b.getTitle()));!B(F(a.a,2))&&b.a&&G(a.a,2,b.a.c);if(a=b.h)wd(this.a,4),b=new kd,G(b.a,1,a.g),c=a.c.height,G(b.a,2,a.c.width),G(b.a,3,c),a=this.a,a.o=b,I(a.a,10,b.a);chrome.runtime.sendMessage({type:"created_clip",clipData:this.a.m(),images:d});this.a=null}else chrome.runtime.sendMessage({type:"salient_images_found",images:d})};
var oe=function(){this.a=x()},pe=new oe;oe.prototype.set=function(a){this.a=a};oe.prototype.reset=function(){this.set(x())};oe.prototype.get=function(){return this.a};var qe=function(a){this.h=a||"";this.i=pe};qe.prototype.a=!0;qe.prototype.c=!0;qe.prototype.g=!1;var re=function(a){return 10>a?"0"+a:String(a)},se=function(a,b){var c=(a.g-b)/1E3,d=c.toFixed(3),e=0;if(1>c)e=2;else for(;100>c;)e++,c*=10;for(;0<e--;)d=" "+d;return d},te=function(a){qe.call(this,a)};y(te,qe);
var ue=function(){w(this.h,this);this.a=new te;this.a.c=!1;this.a.g=!1;this.c=this.a.a=!1;this.g="";this.i={}};
ue.prototype.h=function(a){if(!this.i[a.c]){var b;b=this.a;var c=[];c.push(b.h," ");if(b.c){var d=new Date(a.g);c.push("[",re(d.getFullYear()-2E3)+re(d.getMonth()+1)+re(d.getDate())+" "+re(d.getHours())+":"+re(d.getMinutes())+":"+re(d.getSeconds())+"."+re(Math.floor(d.getMilliseconds()/10)),"] ")}c.push("[",se(a,b.i.get()),"s] ");c.push("[",a.c,"] ");c.push(a.getMessage());b.g&&(d=a.a)&&c.push("\n",d instanceof Error?d.message:d.toString());b.a&&c.push("\n");b=c.join("");if(c=ve)switch(a.h){case dc:we(c, "info",b);break;case gc:we(c,"error",b);break;case hc:we(c,"warn",b);break;default:we(c,"debug",b)}else this.g+=b}};var ve=n.console,we=function(a,b,c){if(a[b])a[b](c);else a.log(c)};
var xe=function(){U.call(this);this.a=new me;ka(this,ja(la,this.a))};y(xe,U);q(xe);var ye=new ue;0!=ye.c&&(nc(),ye.c=!1);var ze=T("image.collections.extension.Content"),Ae=xe.B();ze&&ze.log(ic,"Initializing extension content",void 0);Ae.a.c(Ae);window.full_script_injected=!0;

}catch(e){_DumpException(e)}
// Google Inc.
