try{
'use strict';var f=this,aa=function(){},g=function(a){a.l=function(){return a.s?a.s:a.s=new a}},ba=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=
typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},k=function(a){return"function"==ba(a)},ca=function(a,b,c){return a.call.apply(a.bind,arguments)},da=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);
return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},m=function(a,b,c){m=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ca:da;return m.apply(null,arguments)},ea=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}},fa=Date.now||function(){return+new Date};
var n=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},p=function(a,b){return a<b?-1:a>b?1:0};var q;a:{var x=f.navigator;if(x){var y=x.userAgent;if(y){q=y;break a}}q=""};var z=function(){return-1!=q.indexOf("Edge")||-1!=q.indexOf("Trident")||-1!=q.indexOf("MSIE")};var A=function(){return-1!=q.indexOf("Edge")};var ga=-1!=q.indexOf("Opera")||-1!=q.indexOf("OPR"),B=z(),C=-1!=q.indexOf("Gecko")&&!(-1!=q.toLowerCase().indexOf("webkit")&&!A())&&!(-1!=q.indexOf("Trident")||-1!=q.indexOf("MSIE"))&&!A(),ha=-1!=q.toLowerCase().indexOf("webkit")&&!A(),ia=function(){var a=q;if(C)return/rv\:([^\);]+)(\)|;)/.exec(a);if(B&&A())return/Edge\/([\d\.]+)/.exec(a);if(B)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(ha)return/WebKit\/(\S+)/.exec(a)},D=function(){var a=f.document;return a?a.documentMode:void 0},E=function(){if(ga&&
f.opera){var a=f.opera.version;return k(a)?a():a}var a="",b=ia();b&&(a=b?b[1]:"");return B&&!A()&&(b=D(),b>parseFloat(a))?String(b):a}(),F={},G=function(a){if(!F[a]){for(var b=0,c=n(String(E)).split("."),d=n(String(a)).split("."),e=Math.max(c.length,d.length),h=0;0==b&&h<e;h++){var l=c[h]||"",r=d[h]||"",w=/(\d*)(\D*)/g,t=/(\d*)(\D*)/g;do{var u=w.exec(l)||["","",""],v=t.exec(r)||["","",""];if(0==u[0].length&&0==v[0].length)break;b=p(0==u[1].length?0:parseInt(u[1],10),0==v[1].length?0:parseInt(v[1], 10))||p(0==u[2].length,0==v[2].length)||p(u[2],v[2])}while(0==b)}F[a]=0<=b}},H=f.document,ja=D(),ka=!H||!B||!ja&&A()?void 0:ja||("CSS1Compat"==H.compatMode?parseInt(E,10):5);
var I;if(!(I=!C&&!B)){var J;if(J=B)J=B&&(A()||9<=ka);I=J}I||C&&G("1.9.1");B&&G("9");B&&G(12);var la=function(a){a()},ma=function(a){var b=document.body;b&&a&&la(function(){b.appendChild(a)})},na=function(a,b){la(function(){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=b;else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=b}else{for(var c;c=a.firstChild;)a.removeChild(c);a.appendChild((9==a.nodeType?a:a.ownerDocument||a.document).createTextNode(String(b)))}})};
var K=function(a,b,c){this.h=c;this.g=a;this.i=b;this.c=0;this.a=null};K.prototype.get=function(){var a;0<this.c?(this.c--,a=this.a,this.a=a.next,a.next=null):a=this.g();return a};var oa=function(a,b){a.i(b);a.c<a.h&&(a.c++,b.next=a.a,a.a=b)};var pa=function(a){f.setTimeout(function(){throw a;},0)},L,qa=function(){var a=f.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&-1==q.indexOf("Presto")&&(a=function(){var a=document.createElement("IFRAME");a.style.display="none";a.src="";document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+
"//"+b.location.host,a=m(function(a){if(("*"==d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!z()){var b=new a,c={},d=c;b.port1.onmessage=function(){if(void 0!==c.next){c=c.next;var a=c.o;c.o=null;a()}};return function(a){d.next={o:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in document.createElement("SCRIPT")? function(a){var b=document.createElement("SCRIPT");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};document.documentElement.appendChild(b)}:function(a){f.setTimeout(a,0)}};
var M=function(){this.c=this.a=null},ra=new K(function(){return new N},function(a){a.reset()},100);M.prototype.add=function(a,b){var c=ra.get();c.set(a,b);this.c?this.c.next=c:this.a=c;this.c=c};M.prototype.remove=function(){var a=null;this.a&&(a=this.a,this.a=this.a.next,this.a||(this.c=null),a.next=null);return a};var N=function(){this.next=this.c=this.a=null};N.prototype.set=function(a,b){this.a=a;this.c=b;this.next=null};N.prototype.reset=function(){this.next=this.c=this.a=null};
var ua=function(a,b){O||sa();P||(O(),P=!0);ta.add(a,b)},O,sa=function(){if(f.Promise&&f.Promise.resolve){var a=f.Promise.resolve();O=function(){a.then(va)}}else O=function(){var a=va;!k(f.setImmediate)||f.Window&&f.Window.prototype&&f.Window.prototype.setImmediate==f.setImmediate?(L||(L=qa()),L(a)):f.setImmediate(a)}},P=!1,ta=new M,va=function(){for(var a=null;a=ta.remove();){try{a.a.call(a.c)}catch(b){pa(b)}oa(ra,a)}P=!1};
var R=function(a,b){this.a=0;this.v=void 0;this.g=this.c=this.h=null;this.i=this.m=!1;if(a==wa)Q(this,2,b);else try{var c=this;a.call(b,function(a){Q(c,2,a)},function(a){Q(c,3,a)})}catch(d){Q(this,3,d)}},xa=function(){this.next=this.g=this.c=this.h=this.a=null;this.i=!1};xa.prototype.reset=function(){this.g=this.c=this.h=this.a=null;this.i=!1};
var ya=new K(function(){return new xa},function(a){a.reset()},100),za=function(a,b,c){var d=ya.get();d.h=a;d.c=b;d.g=c;return d},wa=function(){},Ba=function(a){return new R(function(b,c){var d=a.length,e=[];if(d)for(var h=function(a,c){d--;e[a]=c;0==d&&b(e)},l=function(a){c(a)},r=0,w;w=a[r];r++)Aa(w,ea(h,r),l);else b(e)})};R.prototype.then=function(a,b,c){return Ca(this,k(a)?a:null,k(b)?b:null,c)};R.prototype.then=R.prototype.then;R.prototype.$goog_Thenable=!0;
var Aa=function(a,b,c,d){a instanceof R?Da(a,za(b||aa,c||null,d)):a.then(b,c,d)},Da=function(a,b){a.c||2!=a.a&&3!=a.a||Ea(a);a.g?a.g.next=b:a.c=b;a.g=b},Ca=function(a,b,c,d){var e=za(null,null,null);e.a=new R(function(a,l){e.h=b?function(c){try{var e=b.call(d,c);a(e)}catch(t){l(t)}}:a;e.c=c?function(b){try{var e=c.call(d,b);a(e)}catch(t){l(t)}}:l});e.a.h=a;Da(a,e);return e.a};R.prototype.w=function(a){this.a=0;Q(this,2,a)};R.prototype.A=function(a){this.a=0;Q(this,3,a)};
var Q=function(a,b,c){if(0==a.a){if(a==c)b=3,c=new TypeError("Promise cannot resolve to itself");else{var d;if(c)try{d=!!c.$goog_Thenable}catch(e){d=!1}else d=!1;if(d){a.a=1;Aa(c,a.w,a.A,a);return}d=typeof c;if("object"==d&&null!=c||"function"==d)try{var h=c.then;if(k(h)){Fa(a,c,h);return}}catch(l){b=3,c=l}}a.v=c;a.a=b;a.h=null;Ea(a);3!=b||Ga(a,c)}},Fa=function(a,b,c){a.a=1;var d=!1,e=function(b){d||(d=!0,a.w(b))},h=function(b){d||(d=!0,a.A(b))};try{c.call(b,e,h)}catch(l){h(l)}},Ea=function(a){a.m||
(a.m=!0,ua(a.B,a))},Ha=function(a){var b=null;a.c&&(b=a.c,a.c=b.next,b.next=null);a.c||(a.g=null);return b};R.prototype.B=function(){for(var a=null;a=Ha(this);){var b=this.a,c=this.v;if(3==b&&a.c&&!a.i)for(var d=void 0,d=this;d&&d.i;d=d.h)d.i=!1;if(a.a)a.a.h=null,Ia(a,b,c);else try{a.i?a.h.call(a.g):Ia(a,b,c)}catch(e){S.call(null,e)}oa(ya,a)}this.m=!1};var Ia=function(a,b,c){2==b?a.h.call(a.g,c):a.c&&a.c.call(a.g,c)},Ga=function(a,b){a.i=!0;ua(function(){a.i&&S.call(null,b)})},S=pa;
var T=function(){this.c={};this.a={}};g(T);var U=function(a,b,c,d,e){this.reset(a,b,c,d,e)};U.prototype.a=null;var Ja=0;U.prototype.reset=function(a,b,c,d,e){"number"==typeof e||Ja++;d||fa();this.c=b;delete this.a};U.prototype.getMessage=function(){return this.c};var V=function(a){this.h=a;this.c=this.g=this.a=null},W=function(a,b){this.name=a;this.value=b};W.prototype.toString=function(){return this.name};var Ka=new W("SEVERE",1E3),La=new W("CONFIG",700);V.prototype.getChildren=function(){this.c||(this.c={});return this.c};var Ma=function(a){return a.g?a.g:a.a?Ma(a.a):null};
V.prototype.log=function(a,b,c){if(a.value>=Ma(this).value)for(k(b)&&(b=b()),a=new U(a,String(b),this.h),c&&(a.a=c),c="log:"+a.getMessage(),f.console&&(f.console.timeStamp?f.console.timeStamp(c):f.console.markTimeline&&f.console.markTimeline(c)),f.msWriteProfilerMark&&f.msWriteProfilerMark(c),c=this;c;)c=c.a};var X={},Y=null,Na=function(a){Y||(Y=new V(""),X[""]=Y,Y.g=La);var b;if(!(b=X[a])){b=new V(a);var c=a.lastIndexOf("."),d=a.substr(c+1),c=Na(a.substr(0,c));c.getChildren()[d]=b;b.a=c;X[a]=b}return b};
var Z;Z=Na("image.collections.extension.Promises");var S=function(a){Z&&Z.log(Ka,a.toString(),void 0)},Oa=function(a,b,c){return function(d){var e=chrome.runtime.lastError;e?(d=T.l(),a&&(d.a[a]=(d.a[a]||0)+1),c(e.message||"Unknown Chrome API error")):(e=T.l(),a&&(e.c[a]=(e.c[a]||0)+1),b(d))}},Pa=function(a,b){return new R(function(c,d){chrome.tabs.sendMessage(a,b,Oa("chrome.tabs.sendMessage",c,d))})},Qa=function(){return new R(function(a,b){chrome.tabs.getCurrent(Oa("chrome.tabs.getCurrent",a,b))})};
var Ra=function(){};g(Ra);(function(){Ra.l();var a={type:"get_log_history"},b={type:"get_chrome_api_logs"};Qa().then(function(c){c=c.openerTabId;return Ba([Pa(c,a),Pa(c,b)])}).then(function(a){var b;b=document.createElement("pre");na(b,a[0]+"\nChrome API calls:\n"+a[1]);ma(b)})})();

}catch(e){_DumpException(e)}
// Google Inc.
