"""Flatpak install/update automation with Steam shortcut + SteamGridDB
artwork integration, plus the misc emulator/binary updater logic.

Port of utilities/update-software/update-software.sh. The original's
zenity-only GUI wizards (browse-installed-apps-with-actions,
search-Flathub-and-install) are not reimplemented as a GUI here -- they
become plain non-interactive subcommands (`flatpaks search`, `flatpaks
install`, `flatpaks list`, `flatpaks info`) instead, consistent with how
every other interactive script in this conversion became flag-driven.
"""

from __future__ import annotations

import logging
import os
import re
import shutil
import tarfile
import zipfile
from pathlib import Path

import requests

from steamostools.process import run
from steamostools.vdf import shortcuts as steam_shortcuts

logger = logging.getLogger("steamostools.flatpaks")

APP_LOC = Path.home() / "Applications"
BACKUP_LOC = Path("/tmp/update-emulators-backup")
STEAMGRIDDB_CONF = Path.home() / ".steamgriddb"
ICON_CACHE_DIR = Path.home() / ".cache" / "update-software" / "icons"

FLATHUB_API = "https://flathub.org/api/v2"
SGDB_API = "https://www.steamgriddb.com/api/v2"

# name -> flatpak application ID
EMULATOR_FLATPAKS = {
    "dolphin-emu": "org.DolphinEmu.dolphin-emu",
    "DOSBox-Staging": "io.github.dosbox-staging",
    "DuckStation": "org.duckstation.DuckStation",
    "Flycast": "org.flycast.Flycast",
    "MAME": "org.mamedev.MAME",
    "melonDS": "net.kuribo64.melonDS",
    "mGBA": "io.mgba.mGBA",
    "Mupen64Plus (GUI)": "com.github.Rosalie241.RMG",
    "Pegasus": "org.pegasus_frontend.Pegasus",
    "PPSSPP": "org.ppsspp.PPSSPP",
    "PrimeHack": "io.github.shiiion.primehack",
    "RetroArch": "org.libretro.RetroArch",
    "RMG": "com.github.Rosalie241.RMG",
    "RPCS3": "net.rpcs3.RPCS3",
    "shadPS4": "net.shadps4.shadPS4",
    "ScummVM": "org.scummvm.ScummVM",
    "VICE": "net.sf.VICE",
    "Xemu-Emu": "app.xemu.xemu",
}

USER_FLATPAKS = {
    "Protontricks": "com.github.Matoking.protontricks",
    "Heroic Games Launcher": "com.heroicgameslauncher.hgl",
    "Chrome": "com.google.Chrome",
    "Limo": "io.github.limo_app.limo",
    "Kodi": "tv.kodi.Kodi",
}

LUDUSAVI_CONFIG = """\
# Ludusavi configuration
# Generated by SteamOS Tools updater
backups:
  directory: "{home}/.local/share/ludusavi/backups"
  format: zip
  compression: standard
  include:
    - saves
    - settings
    - profiles
    - mods
    - screenshots
    - replays
"""

LUDUSAVI_SERVICE = """\
[Unit]
Description=Ludusavi Backup Service
After=network.target

[Service]
Type=oneshot
ExecStart=/usr/bin/flatpak run com.github.mtkennerly.ludusavi backup
"""

LUDUSAVI_TIMER = """\
[Unit]
Description=Run Ludusavi Backup Daily
Requires=ludusavi-backup.service

[Timer]
OnCalendar=daily
Persistent=true

[Install]
WantedBy=timers.target
"""


class FlatpakInstallError(RuntimeError):
    pass


# ---------------------------------------------------------------------------
# Flatpak install/update
# ---------------------------------------------------------------------------


def install_or_update_flatpak(name: str, app_id: str) -> None:
    """Update app_id if installed, otherwise install it from Flathub.
    Raises FlatpakInstallError if both fail."""
    logger.info("Installing/updating %s", name)
    update_result = run(["flatpak", "--user", "update", app_id, "-y"], check=False)
    if update_result.returncode != 0:
        install_result = run(
            ["flatpak", "install", "--user", "-y", "--noninteractive", "flathub", app_id], check=False
        )
        if install_result.returncode != 0:
            raise FlatpakInstallError(f"Failed to install Flatpak {app_id}")

    run(["flatpak", "override", app_id, "--filesystem=host", "--user"])
    run(["flatpak", "override", app_id, "--share=network", "--user"])

    steam_add_flatpak_shortcut(app_id, name)


def list_installed() -> list[dict]:
    """Return installed Flatpak apps as [{"id", "name", "description", "version"}, ...]."""
    result = run(
        ["flatpak", "list", "--app", "--columns=application,name,description,version"], check=False
    )
    apps = []
    for line in result.stdout.splitlines():
        parts = line.split("\t")
        if len(parts) >= 4:
            apps.append({"id": parts[0], "name": parts[1], "description": parts[2], "version": parts[3]})
    return apps


def remove_deprecated_flatpaks() -> list[str]:
    """Uninstall user Flatpaks Flathub marks end-of-life. Returns the app
    IDs removed (empty list is a legitimate "nothing deprecated" outcome)."""
    result = run(["flatpak", "list", "--user", "--app", "--columns=application,name,options"], check=False)
    removed = []
    for line in result.stdout.splitlines():
        parts = line.split("\t")
        if len(parts) < 3 or "eol=" not in parts[2]:
            continue
        app_id, app_name, options = parts[0], parts[1], parts[2]
        reason = options.split("eol=", 1)[1]
        logger.info("Removing deprecated Flatpak: %s (%s) - %s", app_name, app_id, reason)
        uninstall_result = run(["flatpak", "uninstall", "--user", "-y", app_id], check=False)
        if uninstall_result.returncode == 0:
            removed.append(app_id)
        else:
            logger.error("Failed to uninstall %s", app_id)
    return removed


# ---------------------------------------------------------------------------
# Flathub search/info (replaces the zenity search-and-browse wizard)
# ---------------------------------------------------------------------------


class FlathubClient:
    def __init__(self, session: requests.Session | None = None):
        self.session = session or requests.Session()

    def search(self, query: str) -> list[dict]:
        response = self.session.post(f"{FLATHUB_API}/search", json={"query": query}, timeout=30)
        response.raise_for_status()
        return response.json().get("hits", [])

    def app_info(self, app_id: str) -> dict:
        response = self.session.get(f"{FLATHUB_API}/appstream/{app_id}", timeout=30)
        response.raise_for_status()
        return response.json()


# ---------------------------------------------------------------------------
# Icon resolution
# ---------------------------------------------------------------------------


def find_flatpak_icon(app_id: str) -> Path | None:
    """Locate an icon for a flatpak app id, preferring larger PNG sizes
    then SVG."""
    roots = [
        Path.home() / ".local" / "share" / "flatpak" / "exports" / "share" / "icons" / "hicolor",
        Path("/var/lib/flatpak/exports/share/icons/hicolor"),
    ]
    for size in ("512x512", "256x256", "128x128", "64x64", "48x48", "32x32"):
        for root in roots:
            matches = list((root / size / "apps").glob(f"{app_id}.*")) if (root / size / "apps").is_dir() else []
            if matches:
                return matches[0]
    for root in roots:
        scalable = root / "scalable" / "apps"
        if scalable.is_dir():
            match = scalable / f"{app_id}.svg"
            if match.exists():
                return match
    return None


def resolve_flatpak_icon(app_id: str, *, icon_cache_dir: Path = ICON_CACHE_DIR) -> str:
    """Wraps find_flatpak_icon, but never hands back an SVG: Steam's
    shortcut icon field can't render SVG. An SVG-only app is rasterized to
    PNG via ImageMagick and cached. Returns "" if no usable icon could be
    resolved (missing icon, or missing ImageMagick for an SVG-only app) --
    a legitimate "leave icon unset" outcome, not an error."""
    icon = find_flatpak_icon(app_id)
    if icon is None:
        return ""
    if icon.suffix != ".svg":
        return str(icon)

    if shutil.which("magick") is None:
        logger.warning(
            "Only an SVG icon is available for %s and ImageMagick (magick) is missing; leaving icon unset.",
            app_id,
        )
        return ""

    converted = icon_cache_dir / f"{app_id}.png"
    if not converted.exists():
        icon_cache_dir.mkdir(parents=True, exist_ok=True)
        result = run(
            ["magick", str(icon), "-background", "none", "-resize", "512x512", str(converted)], check=False
        )
        if result.returncode != 0:
            logger.warning("Failed to convert SVG icon for %s; leaving icon unset.", app_id)
            converted.unlink(missing_ok=True)
            return ""
    return str(converted)


# ---------------------------------------------------------------------------
# SteamGridDB artwork
# ---------------------------------------------------------------------------


class SteamGridDBClient:
    def __init__(self, api_key: str, session: requests.Session | None = None):
        self.api_key = api_key
        self.session = session or requests.Session()

    def _get(self, endpoint: str) -> dict:
        response = self.session.get(
            f"{SGDB_API}{endpoint}", headers={"Authorization": f"Bearer {self.api_key}"}, timeout=30
        )
        response.raise_for_status()
        return response.json()

    def find_game_id(self, app_name: str) -> int | None:
        data = self._get(f"/search/autocomplete/{app_name}")
        results = data.get("data") or []
        return results[0]["id"] if results else None

    def download_first_asset(self, endpoint: str, dest: Path) -> bool:
        data = self._get(endpoint)
        results = data.get("data") or []
        if not results or not results[0].get("url"):
            return False
        response = self.session.get(results[0]["url"], timeout=30)
        response.raise_for_status()
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(response.content)
        return True

    def fetch_artwork(self, app_name: str, appid: int, grid_dir: Path) -> None:
        """Fetch grid/hero/logo/icon art for a shortcut's appid. Already
        having an icon cached is treated as "done" -- this shouldn't hammer
        the API every run against ~20 flatpaks."""
        if (grid_dir / f"{appid}_icon.png").exists():
            return

        game_id = self.find_game_id(app_name)
        if game_id is None:
            logger.error("SteamGridDB: no match found for '%s'", app_name)
            return

        assets = [
            (f"/grids/game/{game_id}?dimensions=600x900", grid_dir / f"{appid}p.png", "portrait grid"),
            (f"/grids/game/{game_id}?dimensions=460x215", grid_dir / f"{appid}.png", "grid"),
            (f"/heroes/game/{game_id}", grid_dir / f"{appid}_hero.png", "hero art"),
            (f"/logos/game/{game_id}", grid_dir / f"{appid}_logo.png", "logo"),
            (f"/icons/game/{game_id}", grid_dir / f"{appid}_icon.png", "icon"),
        ]
        for endpoint, dest, label in assets:
            if not self.download_first_asset(endpoint, dest):
                logger.error("SteamGridDB: failed to fetch %s for '%s'", label, app_name)
        logger.info("SteamGridDB: artwork applied for '%s'", app_name)


def steamgriddb_get_api_key(*, conf_path: Path = STEAMGRIDDB_CONF) -> str | None:
    """Read a configured SteamGridDB API key from the environment or the
    config file. Returns None if not configured -- callers must treat
    that as "skip artwork," not an error; there's no interactive prompt
    here (unlike the original bash), since this is a non-interactive CLI
    context now."""
    env_key = os.environ.get("STEAMGRIDDB_API_KEY")
    if env_key:
        return env_key
    if conf_path.exists():
        for line in conf_path.read_text().splitlines():
            if line.startswith("STEAMGRIDDB_API_KEY="):
                return line.split("=", 1)[1].strip().strip("'\"")
    return None


def save_steamgriddb_api_key(key: str, *, conf_path: Path = STEAMGRIDDB_CONF) -> None:
    conf_path.write_text(f"STEAMGRIDDB_API_KEY={key}\n")
    conf_path.chmod(0o600)


# ---------------------------------------------------------------------------
# Steam shortcut integration
# ---------------------------------------------------------------------------


def steam_add_flatpak_shortcut(app_id: str, display_name: str) -> None:
    vdf_files = steam_shortcuts.find_shortcuts_vdf_files()
    if not vdf_files:
        logger.warning(
            "No shortcuts.vdf found - Steam may not be installed or never launched. Skipping Steam shortcut for %s.",
            display_name,
        )
        return

    api_key = steamgriddb_get_api_key()
    appid = steam_shortcuts.generate_appid("/usr/bin/flatpak", display_name)

    for vdf in vdf_files:
        grid_dir = vdf.parent / "config" / "grid"
        icon = ""
        if api_key:
            SteamGridDBClient(api_key).fetch_artwork(display_name, appid, grid_dir)
            icon_path = grid_dir / f"{appid}_icon.png"
            icon = str(icon_path) if icon_path.exists() else resolve_flatpak_icon(app_id)
        else:
            icon = resolve_flatpak_icon(app_id)

        status = steam_shortcuts.add_or_update_flatpak_shortcut(vdf, app_id, display_name, icon)
        logger.info("Steam shortcut for '%s': %s", display_name, status)


# ---------------------------------------------------------------------------
# Core software (Ludusavi + systemd backup timer)
# ---------------------------------------------------------------------------


def setup_ludusavi() -> None:
    install_or_update_flatpak("Ludusavi", "com.github.mtkennerly.ludusavi")

    config_dir = Path.home() / ".var" / "app" / "com.github.mtkennerly.ludusavi" / "config" / "ludusavi"
    config_dir.mkdir(parents=True, exist_ok=True)
    (config_dir / "config.yaml").write_text(LUDUSAVI_CONFIG.format(home=Path.home()))

    unit_dir = Path.home() / ".config" / "systemd" / "user"
    unit_dir.mkdir(parents=True, exist_ok=True)
    (unit_dir / "ludusavi-backup.service").write_text(LUDUSAVI_SERVICE)
    (unit_dir / "ludusavi-backup.timer").write_text(LUDUSAVI_TIMER)

    run(["systemctl", "--user", "enable", "ludusavi-backup.timer"])
    run(["systemctl", "--user", "restart", "ludusavi-backup.timer"])


def update_core_software() -> None:
    logger.info("Copying configs")
    setup_ludusavi()


def update_emulator_software() -> None:
    logger.info("Updating emulators (Flatpaks)")
    for name, app_id in EMULATOR_FLATPAKS.items():
        install_or_update_flatpak(name, app_id)

    # EmuDeck names PCSX2's Qt AppImage differently than upstream releases;
    # keep a compatibility symlink for anything still expecting that name.
    for appimage in APP_LOC.glob("pcsx2*AppImage"):
        (APP_LOC / "pcsx2-Qt.AppImage").unlink(missing_ok=True)
        (APP_LOC / "pcsx2-Qt.AppImage").symlink_to(appimage)
        break


def update_user_flatpaks() -> None:
    for name, app_id in USER_FLATPAKS.items():
        install_or_update_flatpak(name, app_id)
    run(["flatpak", "--user", "--noninteractive", "upgrade"])


def update_user_binaries() -> None:
    logger.info("No user binaries configured currently")


# ---------------------------------------------------------------------------
# Generic binary/archive downloader
# ---------------------------------------------------------------------------


def _github_release_download_url(url: str, name: str, filename_pattern: str | None) -> str:
    is_latest = "latest" in url
    response = requests.get(url, timeout=30)
    response.raise_for_status()
    data = response.json()

    if is_latest:
        assets = data.get("assets", [])
    else:
        prereleases = [r for r in data if r.get("prerelease")]
        assets = prereleases[0]["assets"] if prereleases else []

    urls = [a["browser_download_url"] for a in assets]

    if filename_pattern:
        pattern = re.compile(filename_pattern)
        for candidate in urls:
            if pattern.search(candidate):
                return candidate
    else:
        preference_patterns = [
            r"http.*x.*64.*AppImage$",
            r"http.*AppImage$",
            rf"http.*{re.escape(name)}-.*linux.*x64.*tar\.gz$",
            rf"http.*{re.escape(name)}.*linux.*tar\.gz$",
            rf"http.*{re.escape(name)}.*linux.*tar\.xz$",
        ]
        for pattern_str in preference_patterns:
            pattern = re.compile(pattern_str)
            for candidate in urls:
                if pattern.search(candidate):
                    return candidate

    raise FlatpakInstallError(f"Could not get a download url for {url}")


def resolve_binary_download_url(name: str, url: str, filename_pattern: str | None = None) -> str:
    """Resolve the actual download URL for update_binary's varied input
    shapes: a direct .zip URL, a GitLab releases-API permalink, a GitHub
    releases API URL, or (fallback) the URL itself."""
    if ".zip" in url and "api" not in url:
        return url
    if "gitlab.com/api" in url:
        response = requests.get(url, timeout=30)
        response.raise_for_status()
        data = response.json()
        pattern = re.compile(filename_pattern or rf"{re.escape(name)}.*x64\.AppImage")
        for link in data.get("assets", {}).get("links", []):
            if pattern.search(link.get("name", "")):
                return link["direct_asset_url"]
        raise FlatpakInstallError(f"Could not get a download url for {url}")
    if re.search(r"github\.com.*releases", url):
        return _github_release_download_url(url, name, filename_pattern)
    return url


def update_binary(
    name: str,
    folder_target: str,
    filename_pattern: str,
    url: str,
    dl_type: str,
    *,
    app_loc: Path = APP_LOC,
    download_dir: Path = Path("/tmp"),
) -> Path:
    """Download and install a single-file/archive emulator binary. Handles
    zip/tar.gz/tar.xz/AppImage. Raises FlatpakInstallError if no download
    URL could be resolved."""
    dl_url = resolve_binary_download_url(name, url, filename_pattern or None)
    logger.info("Downloading %s", dl_url)

    response = requests.get(dl_url, stream=True, timeout=60)
    response.raise_for_status()
    dl_filename = dl_url.split("?")[0].rsplit("/", 1)[-1]
    download_path = download_dir / dl_filename
    with download_path.open("wb") as f:
        for chunk in response.iter_content(chunk_size=65536):
            f.write(chunk)

    dest_dir = app_loc / folder_target if folder_target else app_loc
    file_type = dl_type.lower()

    if file_type == "zip":
        dest_dir.mkdir(parents=True, exist_ok=True)
        with zipfile.ZipFile(download_path) as zf:
            zf.extractall(dest_dir)
    elif file_type in ("tar.gz", "tar.xz"):
        dest_dir.mkdir(parents=True, exist_ok=True)
        with tarfile.open(download_path) as tar:
            tar.extractall(dest_dir, filter="data")
        download_path.unlink()
    elif file_type == "appimage":
        dest_dir.mkdir(parents=True, exist_ok=True)
        target = dest_dir / dl_filename
        shutil.move(download_path, target)
        target.chmod(target.stat().st_mode | 0o111)
    else:
        raise FlatpakInstallError(f"Don't know how to handle download type: {dl_type}")

    return dest_dir


# ---------------------------------------------------------------------------
# CLI wiring
# ---------------------------------------------------------------------------


def register_subparser(subparsers) -> None:
    parser = subparsers.add_parser(
        "update-software", help="Flatpak/emulator software updater with Steam shortcut integration"
    )
    sub = parser.add_subparsers(dest="update_software_command", required=True)

    sub.add_parser("all", help="update core software, emulators, user binaries, user flatpaks").set_defaults(
        func=_cmd_all
    )
    sub.add_parser("core", help="update core software (Ludusavi + backup timer)").set_defaults(func=_cmd_core)
    sub.add_parser("emulators", help="update emulator Flatpaks and binaries").set_defaults(func=_cmd_emulators)
    sub.add_parser("user-flatpaks", help="update user Flatpaks").set_defaults(func=_cmd_user_flatpaks)
    sub.add_parser("user-binaries", help="update user binaries").set_defaults(func=_cmd_user_binaries)
    sub.add_parser("remove-deprecated", help="uninstall end-of-life user Flatpaks").set_defaults(
        func=_cmd_remove_deprecated
    )

    flatpaks_parser = subparsers.add_parser("flatpaks", help="browse/manage Flatpaks via Flathub")
    flatpaks_sub = flatpaks_parser.add_subparsers(dest="flatpaks_command", required=True)

    search = flatpaks_sub.add_parser("search", help="search Flathub")
    search.add_argument("query")
    search.set_defaults(func=_cmd_search)

    info = flatpaks_sub.add_parser("info", help="show Flathub app details")
    info.add_argument("app_id")
    info.set_defaults(func=_cmd_info)

    install = flatpaks_sub.add_parser("install", help="install/update a Flatpak by app ID")
    install.add_argument("app_id")
    install.add_argument("--name", default=None, help="display name for the Steam shortcut (default: app_id)")
    install.set_defaults(func=_cmd_flatpak_install)

    flatpaks_sub.add_parser("list", help="list installed Flatpaks").set_defaults(func=_cmd_flatpak_list)


def _cmd_all(args) -> int:
    update_core_software()
    update_emulator_software()
    update_user_binaries()
    update_user_flatpaks()
    return 0


def _cmd_core(args) -> int:
    update_core_software()
    return 0


def _cmd_emulators(args) -> int:
    update_emulator_software()
    return 0


def _cmd_user_flatpaks(args) -> int:
    update_user_flatpaks()
    return 0


def _cmd_user_binaries(args) -> int:
    update_user_binaries()
    return 0


def _cmd_remove_deprecated(args) -> int:
    removed = remove_deprecated_flatpaks()
    logger.info("Removed %d deprecated Flatpak(s)", len(removed))
    return 0


def _cmd_search(args) -> int:
    hits = FlathubClient().search(args.query)
    for hit in hits:
        print(f"{hit.get('app_id')}\t{hit.get('name')}\t{hit.get('summary', '')}")
    return 0


def _cmd_info(args) -> int:
    info = FlathubClient().app_info(args.app_id)
    for key in ("name", "summary", "developer_name", "project_license", "installs_last_month"):
        print(f"{key}: {info.get(key, 'N/A')}")
    return 0


def _cmd_flatpak_install(args) -> int:
    install_or_update_flatpak(args.name or args.app_id, args.app_id)
    return 0


def _cmd_flatpak_list(args) -> int:
    for app in list_installed():
        print(f"{app['id']}\t{app['name']}\t{app['version']}")
    return 0
